name: Test the development workflow

on:
  push:
    branches: [ master ]
  pull_request:

concurrency:
  group: ${{
    ( github.ref == 'refs/heads/master' &&
    format('{0}/{1}', github.run_id, github.run_attempt) )
    ||
    format('{0}/{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  test-zkllvm-workflow:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Compile a circuit
        run: scripts/ci.sh --docker compile

      - name: Make constraint and assignment table (optional)
        run: scripts/ci.sh --docker run_assigner

      - name: Build a statement for the Proof Market
        run: scripts/ci.sh --docker build_statement

      - name: Calculate a proof
        run: scripts/ci.sh --docker prove
